# number or rows and columns in cell grid
default_cell_rows: 10
default_cell_columns: 10

# size of cells on start -> int or (int, int)
default_cell_size: [40, 40]

# path to directory containing tile sets
default_tile_path: 'tilesets'

# tile set that is loaded on program start
default_tile_set: 'basic_tiles_with_rotations'

# time between collapsing cells in seconds
default_solver_delay: 0.01
